[versions]
agp = "8.4.1"
kotlin = "1.9.0"
ksp = "1.9.0-1.0.13"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.8.3"
activityCompose = "1.9.0"
composeBom = "2024.06.00"
documentScanner = "16.0.0-beta1"
textRecognition = "19.0.0"
firebaseBom = "33.0.0"
firebaseAuth = "23.0.0"
firebaseCrashlytics = "19.0.0"
firebaseAnalytics = "22.0.0"
firebaseRemoteConfig = "22.0.0"
room = "2.6.1"
navigationCompose = "2.7.7"
hiltNavigationCompose = "1.2.0"
hiltCompiler = '1.2.0'
daggerHiltAndroid = "2.49"
coil = "2.5.0"
gson = '2.10.1'
splashScreen = "1.0.1"
adaptiveM3 = "1.0.0-beta04"
kotlinParcelize = "2.0.0"
daggerHiltAndroidGradle = "2.43.2"
composeIcons = "1.6.8"
googleGsmService = "4.4.2"
crashlytics = "3.0.1"
lottie = "5.2.0"
accompanist = "0.12.0"
accompanistPermissions = "0.28.0"
playAuth = "21.2.0"
playReview = "2.0.1"
playUpdate = "2.1.0"
firebaseMessagingKtx = "24.0.0"
prettyTime = "5.0.4.Final"
composeShimmer = "1.3.0"
composeMarkdown = "0.5.0"
pdfViewer = "2.1.1"
dataStore = "1.1.1"
playAds = "23.2.0"
billingVersion="7.0.0"
glance="1.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
#lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycleRuntimeKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
androidx-compose-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeIcons" }

#glance
androidx-glance-appwidget = {group ="androidx.glance" , name="glance-appwidget" , version.ref="glance"}
androidx-glance-m3 = { group="androidx.glance" , name="glance-material3" , version.ref="glance"}

#adaptive ui
androidx-compose-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "adaptiveM3" }
androidx-compose-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "adaptiveM3" }
androidx-compose-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "adaptiveM3" }
androidx-compose-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
#coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

#accompanist
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissions" }


#lottie
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }


#markdown
compose-markdown = { group = "com.github.jeziellago", name = "compose-markdown", version.ref = "composeMarkdown" }



#shimmer
compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "composeShimmer" }


#time formating

android-prettytime = { group = "org.ocpsoft.prettytime", name = "prettytime", version.ref = "prettyTime" }

#pdf viewer
pdf-viewer = { group = "io.github.afreakyelf", name = "Pdf-Viewer", version.ref = "pdfViewer" }


# hilt and dagger
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltCompiler" }
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHiltAndroid" }
dagger-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerHiltAndroid" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

#room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

#navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

#firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuth" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebaseCrashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebaseAnalytics" }
firebase-remoteconfig = { group = "com.google.firebase", name = "firebase-config-ktx", version.ref = "firebaseRemoteConfig" }
firebase-functions = { group = "com.google.firebase", name = "firebase-functions-ktx" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-appcheck = { group = "com.google.firebase", name = "firebase-appcheck-debug" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
firebase-inappmessaging = { group = "com.google.firebase", name = "firebase-inappmessaging" }
firebase-inappmessaging-display = { group = "com.google.firebase", name = "firebase-inappmessaging-display" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx" }

#gson
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

#play
google-play-document-scanner = { group = "com.google.android.gms", name = "play-services-mlkit-document-scanner", version.ref = "documentScanner" }
google-play-text-recognition = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition", version.ref = "textRecognition" }
google-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playAuth" }
google-play-review = { group = "com.google.android.play", name = "review", version.ref = "playReview" }
google-play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "playReview" }
google-play-update = { group = "com.google.android.play", name = "app-update", version.ref = "playUpdate" }
google-play-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "playUpdate" }
google-play-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playAds" }
google-play-billing= { group = "com.android.billingclient", name = "billing", version.ref = "billingVersion" }
google-play-billing-ktx= { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billingVersion" }

#data store
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "daggerHiltAndroid" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlinParcelize" }
#dagger-hilt-android-gradle={id="hilt-android-gradle-plugin",version.ref="daggerHiltAndroidGradle"}

google-gsm-service = { id = "com.google.gms.google-services", version.ref = "googleGsmService" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }

