package app.dfeverx.ninaiva.models

val LEVEL_EMOJI_NAME = listOf(
    Pair("🐌", "Snail"),
    Pair("🐢", "Turtle"),
    Pair("🐇", "Rabbit"),
    Pair("🚶‍♂️", "Stroll"),
    Pair("🏃‍♂️", "Sprint"),
    Pair("🚲", "Cycle"),
    Pair("🚗", "Drive"),
    Pair("🚤", "Speedboat"),
    Pair("🛸", "UFO"),
    Pair("🚁", "Helicopter"),
    Pair("✈️", "Flight"),
    Pair("🚀", "Rocket"),
    Pair("🦅", "Eagle"),
    Pair("🌊", "Wave"),
    Pair("🌈", "Rainbow"),
    Pair("💨", "Wind"),
    Pair("🌪️", "Tornado"),
    Pair("🌪️", "Hurricane"),
    Pair("⚡️", "Flash"),
    Pair("💥", "Explosion"),
    Pair("🔥", "Fire"),
    Pair("☀️", "Sun"),
    Pair("🌤️", "Sun Behind Cloud"),
    Pair("🌧️", "Rain Cloud"),
    Pair("⛈️", "Storm Cloud"),
    Pair("🌩️", "Lightning"),
    Pair("🌨️", "Snowfall"),
    Pair("🌫️", "Fog"),
    Pair("🎈", "Balloon"),
    Pair("🏞️", "National Park"),
    Pair("🏙️", "Cityscape"),
    Pair("🌃", "Night City"),
    Pair("🌌", "Milky Way"),
    Pair("🌠", "Shooting Star"),
    Pair("🪐", "Planet"),
    Pair("🌟", "Star"),
    Pair("⛰️", "Mountain"),
    Pair("🏔️", "Snowy Mountain"),
    Pair("🏜️", "Desert"),
    Pair("🏝️", "Island")
)